highco_timeline:
    db_driver: orm
    notifiers:
        - highco.timeline.unread_notifications
    timeline_action_manager: highco.timeline_action_manager.default
    filters:
        - highco.timeline.filter.duplicate_key # Filter duplicate keys
        - spy_timeline_demo_filter # hydrate user (subject)
        # On this app, we cannot use data_hydrator, because we do not use entity actually
        #- highco.timeline.filter.data_hydrator  # Hydrate data from doctrine to get TimelineAction instead of ID
    spread:
        on_me: true                             # Spread each action on subject too
        on_global_context: true                 # Spread automatically on global context
    provider: highco.timeline.provider.redis    # write your own
    delivery: immediate                         # wait
    render:
        path:     'SpyDemoBundle:Timeline'
        fallback: 'SpyDemoBundle:Timeline:default.html.twig'
